### ISSUE TITLE
Able to hand Sauron titles as Dol Guldur

### ISSUE THREAD

**Issue by blackbird5598** [MattTheLegoman/RealmsInExile#743] opened 2023-02-27 03:59 UTC
![image](https://user-images.githubusercontent.com/125709421/221471038-d5ae0e51-f937-473e-a7e5-6e8e41ef57f1.png)

For some reason when you play as Dol Guldur you can hand out titles to Sauron even though you're independent. Another tester has attempted to replicate this problem with other nations but so far has only had the problem with Dol Guldur.

**Comment by JukeJukestar** [comment] 2023-02-27 16:22
I believe this may be the case because Sauron is the head of faith of lidless eye - Similar to the pope.

**Comment by jj248** [comment] 2023-02-28 10:08
> I believe this may be the case because Sauron is the head of faith of lidless eye - Similar to the pope.

Agreed - this is normal behaviour for granting land to head of faiths.  Closing as it is working as designed. 
![image](https://user-images.githubusercontent.com/26043074/221821912-48bf7634-68bf-406b-8fc0-4a8c02f1b4b7.png)

**Closed by jj248** 2023-02-28 10:08 UTC
Labels: bug, oddity, priority: low
