### ISSUE TITLE
Add and assign 'Veterans of Palisor' trait

### ISSUE THREAD

**Issue by jj248** [MattTheLegoman/RealmsInExile#517] opened 2022-10-06 08:57 UTC
Avari equivalent of two trees historic trait.

**Comment by jj248** [comment] 2023-02-14 23:22
Icon of Tower of Babel with sword running through it?

**Comment by jj248** [comment] 2023-02-15 11:11
Done - icon could perhaps use some finessing, but it's the best I can do!  Photoshop file attached if someone more capable wants to try to improve / revamp.

Otherwise, over to testers for balance thoughts.  Note this is a historic trait for scripted characters, a lot like light of the two trees.

[pallisortrait.zip](https://github.com/MattTheLegoman/RealmsInExile/files/10742245/pallisortrait.zip)

**Comment by JukeJukestar** [comment] 2023-02-17 13:31
Working as intended. Its quite powerful but I think thats in line with what its supposed to do.
In the future, look into giving it to more avari characters.
closing for now.

**Closed by JukeJukestar** 2023-02-17 13:31 UTC
Labels: good first issue, priority: low, scripting
