### ISSUE TITLE
Orcs marrying humans 

### ISSUE THREAD

**Issue by Chief305** [MattTheLegoman/RealmsInExile#314] opened 2022-02-23 11:30 UTC
![20220223040300_1](https://user-images.githubusercontent.com/99970173/155311045-2e56cc4f-dcf2-45ec-97de-a428ca9097ca.jpg)
![20220223040146_1](https://user-images.githubusercontent.com/99970173/155311218-43177aeb-31d1-4b6d-9b98-43666f8438d9.jpg)
 I found two unions with orc's and humans

**Comment by Remerod** [comment] 2022-02-23 12:00
happened to me to, i don't believe humans and orcs should be able to marry if i am correct?

**Comment by Vierwood** [comment] 2022-02-23 14:09
This seems to be caused by Fallen Maiar/Fallen Istari spawned characters that aren't being converted to Orcs quickly enough, thus giving them a window to marry humans.

**Comment by Chief305** [comment] 2022-02-24 23:48
havent seen any but i still keep an eye out

**Comment by Jermanlordy** [comment] 2022-02-26 16:50
i gave 11 orcs each a barony and none of them married any human they all married other orcs.

**Comment by Remerod** [comment] 2022-02-26 16:51
with having 2 tester double checking this, i think we're safe to assume that the latest update have fixed this issue! So I'm closing it

**Closed by Remerod** 2022-02-26 16:51 UTC
Labels: bug, oddity, priority: medium
