### ISSUE TITLE
Game crashes when player challenges characters to trial by combat

### ISSUE THREAD

**Issue by savagesach** [MattTheLegoman/RealmsInExile#639] opened 2023-02-01 00:01 UTC
When I try challenging other characters to a trial by combat, it always crashes. I have tested this with Thranduil, Khuddrig Vangaris, and Khamul.

**Comment by jj248** [comment] 2023-02-04 11:35
Duplicate of #622 - closing.

**Closed by jj248** 2023-02-04 11:35 UTC
Labels: bug, priority: critical
