### ISSUE TITLE
Two versions of Gondor ruler appear on 'The Lidless Eye Closes' pop-up

### ISSUE THREAD

**Issue by RedArkady** [MattTheLegoman/RealmsInExile#78] opened 2021-05-15 18:27 UTC
![Crusader Kings III Screenshot 2021 05 15 - 19 09 29 56](https://user-images.githubusercontent.com/20355423/118374344-7e706280-b5b3-11eb-8415-cb603a8b625c.png)

**Comment by jj248** [comment] 2021-05-15 21:02
Added a trigger so that this doesn't fire for the ruler of Gondor.

**Comment by RedArkady** [comment] 2021-05-19 17:08
The 'Lidless eye' pop-up no longer appears. Is that was what originally intended? It read well as a follow-up to 'the Black Tower Falls' pop-up, but understandable if it's just meant for others.

**Comment by jj248** [comment] 2021-05-19 18:05
Gondor get their own separate "The Black Tower Falls" event on victory (id = gondor.2012) so the global announcement is disabled for them to avoid doubling up on announcement messages.

Fix working as intended - closing. :)

**Closed by jj248** 2021-05-19 18:05 UTC
Labels: bug, priority: low
