### ISSUE TITLE
Suggestion: Orcish Genocide of Free Peoples Idea

### ISSUE THREAD

**Issue by RoughlyTheSizeOfAMOROOON** [MattTheLegoman/RealmsInExile#469] opened 2022-08-10 22:31 UTC
Suggestion: Orcish decision to do a little bit of trolling (read; genocide and enslavement) of counties that you control; changes culture, faith and maybe buildings. Basically the 'remove orcish building' idea Kyrenic just put out. It happens very swiftly, but  you are 99% going to get an uprising in the places you're doing it. Also, costs scaling gold/prestige to do and perhaps gives you mega opinion maluses with good-faith dudes (sure, may not change much since they already hate you, but maybe it'll get you some rivalries)

Implementation: A decision, maybe? Let's say you're an Orc and you've got control of Minith Tirith. Congrats, but you're surrounded by Tarks who hate you. Solution: bring in some beefy Uruks to turn all those Tarks into meat and slaves.

**Comment by Remerod** [comment] 2022-08-10 22:35
Gonna mention this again: i'm not super against it but we should not remove to much of main mechanics, like promote cultures. A decision like this needs to be very thought on and how it will impact the game and time spent doing it.
This issue made by @Kyrenic  mention is https://github.com/MattTheLegoman/RealmsInExile/issues/468

**Comment by Kyrenic** [comment] 2022-08-10 22:40
We could add a bonus to the promote culture through the Orc society tradition like that religious thing does?

**Comment by Kyrenic** [comment] 2022-08-11 14:47
> Gonna mention this again: i'm not super against it but we should not remove to much of main mechanics, like promote cultures. A decision like this needs to be very thought on and how it will impact the game and time spent doing it. This issue made by @Kyrenic mention is #468

I've added a steward councillor task to test this. The way I see it, it's not a removal of a main game mechanic, but more like an expansion of a main game mechanic

**Comment by JukeJukestar** [comment] 2022-08-26 09:23
Could we close this since its basically a duplicate of #468 and continue conversation there? @RoughlyTheSizeOfAMOROOON

**Closed** 2022-08-26 14:26 UTC
Labels: new feature, suggestion, balance, research
